# fly.toml file generated for peace-inioluola-tribute on 2023-02-09T18:15:40+01:00

app = "peace-inioluola-tribute"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[build]
  image = "huboh/pocketbase:peace"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[mounts]
  destination = "/pb/pb_data"
  source = "pb_data"

[[services]]
  http_checks = []
  internal_port = 8090
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
